
name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyformance wavefront-sdk-python flake8
        python -m pip install flake8-colors flake8-docstrings flake8-import-order
        python -m pip install pep-naming pylint psutil
    - name: Flake8
      run: python -m flake8
    - name: Pylint
      run: python -m pylint wavefront_pyformance
    - name: Test
      run: python -m unittest discover
    - name: Validate Version has updated
      run: test -n "$(git diff -G version= origin/master HEAD -- setup.py)""